# Generated by Django 3.0.5 on 2020-04-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200412_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='pharmacie_adress',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='pharmacie_commune',
            field=models.CharField(blank=True, choices=[('ixelles', 'Ixelles'), ('eterbeek', 'Eterbeek'), ('uccle', 'Uccle'), ('bruxelles', 'Bruxelles'), ('anderlecht', 'anderlecht'), ('ganshoren', 'Ganshoren'), ('jette', 'Jette'), ('berchem-Sainte-Agathe', 'Berchem-Sainte-Agathe'), ('saint-Gilles', 'Saint-Gilles'), ('molenbeek-Saint-Jean', 'Molenbeek-Saint-Jean'), ('saint-Josse-ten-Noode', 'Saint-Josse-ten-Noode'), ('woluwe-Saint-Lambert', 'Woluwe-Saint-Lambert '), ('woluwe-Saint-Pierre', 'Woluwe-Saint-Pierre'), ('watermael-Boitsfort', 'Watermael-Boitsfort'), ('audergem', 'Audergem'), ('evere', 'Evere'), ('schaerbeek', 'Schaerbeek'), ('koekelberg', 'Koekelberg')], max_length=30, null=True),
        ),
    ]
