# Generated by Django 3.0.5 on 2020-04-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200414_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(blank=True, max_length=30, null=True)),
                ('message_firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('message_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_objet', models.CharField(blank=True, max_length=30, null=True)),
                ('messag_text', models.TextField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
